### ISSUE TITLE
Start entry in menu bar shows up twice

### ISSUE THREAD

**Issue by onnotasler** [pfadfinder-konstanz/hugo-dpsg#2]
The first entry in the menu bar, titled "Start" shows up twice in the example page. The only way to get rid of it is to keep the "[menu]" part of the config.toml, while deleting "[[menu.main]] id = Start". Deleting the whole menu section will keep the double entry. I do not think that this is the intended behaviour.

Also, is it possible to turn off the most recent blog posts on the menu bar? I find that a bit unnecessary, as those are already shown on the widget.

**Comment by mxmehl** [comment]
Ah, the example site is a bit tricky as it has a few requirements I cannot change in order to be displayed correctly [here](https://themes.gohugo.io//theme/hugo-dpsg/).

Please have a look at the recommended configuration as written in the README, or look at the [reference implementation](https://github.com/pfadfinder-konstanz/website).

You should be able to control all menu entries in the `.md` files' front matter.

As for the second entry, could you please open a separate issue? Thanks!

**Comment by onnotasler** [comment]
Ah, with the reference implementation to compare, I got it working! Thank you!
